# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20170222_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-created', '-lastUpdated']},
        ),
    ]
