# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20170228_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='width_Field',
            new_name='widthasasf_Field',
        ),
    ]
