# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 02:34
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20170228_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='widthasasf_Field',
            new_name='width_Field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_Field', null=True, upload_to=Posts.models.uploadLoc, width_field='width_Field'),
        ),
    ]
