# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-04 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_auto_20170304_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2017, 3, 4, 4, 1, 33, 673140, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
